INSERT INTO GIT_REPOSITORY(FULL_NAME, DESCRIPTION, CLONE_URL, STARS, CREATED_AT)VALUES ('HubertKarw/test1', 'desc','url1', 1,'2024-11-11');
INSERT INTO GIT_REPOSITORY(FULL_NAME, DESCRIPTION, CLONE_URL, STARS, CREATED_AT)VALUES ('HubertKarw/test2', 'no-desc','url[',0,'2024-11-11');
INSERT INTO GIT_REPOSITORY(FULL_NAME, DESCRIPTION, CLONE_URL, STARS, CREATED_AT)VALUES ('HubertKarw/test3', null, 'urll',10,'2024-11-11');
INSERT INTO GIT_REPOSITORY(FULL_NAME, DESCRIPTION, CLONE_URL, STARS, CREATED_AT)VALUES ('HubertKarw/test4', 'description','url12',11,'2024-11-11');
INSERT INTO GIT_REPOSITORY(FULL_NAME, DESCRIPTION, CLONE_URL, STARS, CREATED_AT)VALUES ('HubertKarw/test5', 'desc','lone-url',99,'2024-11-11');